version: "2"
services:
  spacedeck:
    build: .
    container_name: spacedeck
    ports:
      - "9666:9666"
    volumes:
      - ./storage:/app/storage
      - ./database.sqlite:/app/database.sqlite
